//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Otobilet {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Otobilet.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button1 {
            get {
                return ResourceManager.GetString("button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkçe benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button11 {
            get {
                return ResourceManager.GetString("button11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string button12 {
            get {
                return ResourceManager.GetString("button12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Erkek benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ErkekRbtn {
            get {
                return ResourceManager.GetString("ErkekRbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Giriş Yap benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string GirisBtn {
            get {
                return ResourceManager.GetString("GirisBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kadın benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KadinRbtn {
            get {
                return ResourceManager.GetString("KadinRbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Geri Dön benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KayitGeriBtn {
            get {
                return ResourceManager.GetString("KayitGeriBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Kayıt Ol benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string KayitKayitBtn {
            get {
                return ResourceManager.GetString("KayitKayitBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parola benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Otobüs Bilet Otomasyonu: Otobilet benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ayarlar benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label12 {
            get {
                return ResourceManager.GetString("label12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Otobilet&apos;e Hemen Kayıt Ol! benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ad: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label14 {
            get {
                return ResourceManager.GetString("label14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Soyad: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label15 {
            get {
                return ResourceManager.GetString("label15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label16 {
            get {
                return ResourceManager.GetString("label16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Telefon: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label17 {
            get {
                return ResourceManager.GetString("label17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dil Seçenekleri: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label30 {
            get {
                return ResourceManager.GetString("label30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   E-posta benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cinsiyet: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Şifre Tekrar: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string label7 {
            get {
                return ResourceManager.GetString("label7", resourceCulture);
            }
        }
    }
}
